# Welcome to your law firm website. Change the values in this file to configure your site. 

# The name of your law firm
title: Free Firm Site LLP

# The email address of your law firm. This will be displayed on the website, and messages sent using the contact form will be sent to this address.
email: "info@firm.com"

# The phone number of your law firm. This will be displayed on the website.
phone: "+1 650 391 0000"

# The description of your website. This will be displayed in the footer of the website
description: >- # this means to ignore newlines until "baseurl:"
  Law Firm is the leading full-service firm in the San Francisco Bay Area. No matter your issue, we have your covered.

# The tagline of your website. This will be displayed on the home page of your website
tagline: Free, Flexible, Effective

# The address of your firm. This will be displayed in the footer of your website
address_1: "1535 Mission St."
address_2: "San Francisco, CA, 94103"

# It would not be a legal website without a disclaimer! This will be displayed in the footer of your website
disclaimer: "Attorney advertisement. This information is not intended to create, and receipt of it does not constitute an attorney-client relationship. Internet subscribers and online readers should not act upon this information without seeking professional counsel. Do not send us information that is confidential until you speak with one of our attorneys and obtain authorization to send that information to us."

# The secondary tagline of your website. This will be displayed on the home page of your website, under the primary tagline
secondary_tagline: A free legal website template, yours to use and customize.

# The url of the main image of your website. This image is displayed front and center on the home page. 
background_image: https://images.unsplash.com/photo-1422226256160-9b266e308ea6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2853&q=80

repository: "nicolas-van/bootstrap-4-github-pages"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  - posts

#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
